# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Orbmu2k.nvidiaProfileInspector
PackageVersion: 3.0.2.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: nvidiaProfileInspector.exe
    PortableCommandAlias: nvidiaProfileInspector
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Orbmu2k/nvidiaProfileInspector/releases/download/v3.0.2.1/nvidiaProfileInspector.zip
    InstallerSha256: ""
ManifestType: installer
ManifestVersion: 1.10.0
